import { daftarkanTerjemahan } from "@/stores/i18n"

// Tabel terjemahan Indonesia → Inggris untuk teks di dalam halaman.
// Kunci = kalimat aslinya, jadi menambah teks baru di view tidak pernah
// membuat UI rusak: yang belum ada di sini tampil apa adanya.
daftarkanTerjemahan({
  // ---- umum ----
  "Batal": "Cancel",
  "Simpan": "Save",
  "Simpan Perubahan": "Save Changes",
  "Hapus": "Delete",
  "Tambah": "Add",
  "Tutup": "Close",
  "Muat ulang": "Reload",
  "Kembali ke dashboard": "Back to dashboard",
  "Pasang": "Install",
  "Pasang di Components": "Install in Components",
  "Hentikan": "Stop",
  "Jalankan": "Start",
  "Sambung": "Connect",
  "Putus": "Disconnect",
  "Aktif": "Active",
  "Nonaktif": "Inactive",
  "Terpasang": "Installed",
  "Belum Terpasang": "Not Installed",
  "Terkoneksi": "Connected",
  "Terputus": "Disconnected",
  "Belum terpasang": "Not installed",
  "opsional": "optional",
  "dibutuhkan": "required by",
  "terpasang": "installed",
  "dtk": "s",

  // ---- dashboard ----
  "Menunggu data metrik dari server…": "Waiting for metrics from the server…",
  "Ringkasan": "Summary",
  "Proses": "Processes",
  "Sesi terminal": "Terminal sessions",
  "Tersedia": "Available",
  "Masuk": "In",
  "Keluar": "Out",
  "Tidak terdeteksi": "Not detected",
  "tidak terdeteksi": "not detected",
  "Pemakaian CPU total": "Total CPU usage",
  "Pemakaian RAM": "RAM usage",
  "Lihat semua": "View all",
  "core": "cores",
  "mount": "mounts",
  "terpakai": "used",
  "dari": "of",
  "sisa": "free",
  "Nama kartu diambil dari Windows lewat interop WSL — util dan VRAM tidak ikut terbaca dari sana.":
    "The card name comes from Windows over WSL interop — utilization and VRAM are not available from there.",
  "Driver tidak mengekspos util/VRAM (cukup umum di amdgpu lawas atau LXC passthrough).":
    "Driver does not expose utilisation/VRAM (common on older amdgpu or LXC passthrough).",

  // ---- components ----
  "Hanya yang belum terpasang": "Only not installed",
  "Memasang": "Installing",
  "Memproses": "Working",
  "detik berjalan — jangan tutup halaman ini": "seconds elapsed — do not close this page",
  "Runtime & tunnel": "Runtime & tunnels",
  "Berbagi file & jaringan": "File sharing & network",
  "Keamanan": "Security",
  "Utilitas": "Utilities",
  "Semua komponen di katalog sudah terpasang.": "Every component in the catalog is installed.",
  "Gagal memuat daftar komponen. Pastikan helper daemon aktif.":
    "Failed to load the component list. Make sure the helper daemon is running.",

  // deskripsi komponen (teks dari backend)
  "Container runtime + Compose v2. Dipakai halaman System → Docker.":
    "Container runtime + Compose v2. Used by System → Docker.",
  "Runtime JavaScript + npm. Dibutuhkan komponen 9router.":
    "JavaScript runtime + npm. Required by the 9router component.",
  "Mesh VPN berbasis WireGuard, akses remote tanpa buka port.":
    "WireGuard-based mesh VPN, remote access without opening ports.",
  "Cloudflare Tunnel — ekspos service tanpa port forwarding.":
    "Cloudflare Tunnel — expose services without port forwarding.",
  "Dijalankan dari {0}": "Started from {0}",
  "VPN peer-to-peer, dikonfigurasi di Settings → Network.":
    "Peer-to-peer VPN, configured in Settings → Network.",
  "Gateway API AI lokal (butuh Node.js).": "Local AI API gateway (requires Node.js).",
  "Server DNS lengkap (blocklist, DoH/DoT, cache) — web console di port 5380, login awal admin/admin. Pemasangannya mematikan systemd-resolved.":
    "Full DNS server (blocklists, DoH/DoT, caching) — web console on port 5380, first login admin/admin. Installing it disables systemd-resolved.",
  "Server file sharing SMB/CIFS. Halaman File manager → Samba butuh ini.":
    "SMB/CIFS file sharing server. Required by File manager → Samba.",
  "Server NFS untuk klien Linux/Unix.": "NFS server for Linux/Unix clients.",
  "Klien untuk me-mount share SMB dari server lain.":
    "Client for mounting SMB shares from other servers.",
  "mDNS/Bonjour — server dikenali sebagai <hostname>.local di LAN.":
    "mDNS/Bonjour — the server is reachable as <hostname>.local on the LAN.",
  "Gabungkan beberapa disk jadi satu mount point (union filesystem).":
    "Combine several disks into one mount point (union filesystem).",
  "Firewall sederhana di atas iptables. Halaman Settings → Firewall butuh ini.":
    "Simple firewall on top of iptables. Required by Settings → Firewall.",
  "Blokir IP otomatis setelah percobaan login gagal berulang.":
    "Automatically ban IPs after repeated failed logins.",
  "Baca sensor suhu/kipas motherboard dan CPU.":
    "Read motherboard and CPU temperature/fan sensors.",
  "Kesehatan disk lewat S.M.A.R.T.": "Disk health via S.M.A.R.T.",
  "Info dan kesehatan SSD NVMe.": "NVMe SSD info and health.",
  "Integrasi VM dengan host Proxmox/QEMU (shutdown rapi, info IP).":
    "VM integration with the Proxmox/QEMU host (clean shutdown, IP info).",
  "Monitor proses interaktif di terminal.": "Interactive process monitor in the terminal.",
  "Analisis pemakaian disk per folder.": "Analyse disk usage per folder.",
  "Ringkasan sistem bergaya ASCII art untuk halaman Terminal.":
    "ASCII-art system summary for the Terminal page.",
  "Backup terenkripsi dan ter-deduplikasi.": "Encrypted, deduplicated backups.",
  "Software opsional yang tidak ikut di instalasi dasar Ubuntu/Debian":
    "Optional software not included in a base Ubuntu/Debian install",

  // ---- samba ----
  "Kelola folder sharing jaringan lokal (smbd)": "Manage local network shares (smbd)",
  "Tambah Share": "Add Share",
  "Tambah User": "Add User",
  "User Samba": "Samba Users",
  "Kredensial login share — terpisah dari password akun Linux":
    "Share login credentials — separate from Linux account passwords",
  "Nama Share": "Share Name",
  "%U diganti nama user yang menyambung, jadi /home/%U/DATA/Documents memberi tiap akun folder datanya sendiri.": "%U is replaced with the connecting user's name, so /home/%U/DATA/Documents gives every account its own data folder.",
  "Path Folder": "Folder Path",
  "Komentar / Deskripsi": "Comment / Description",
  "User yang boleh mengakses": "Users allowed to access",
  "semua user Samba": "all Samba users",
  "dari smb.conf": "from smb.conf",
  "dikelola di smb.conf": "managed in smb.conf",
  "Username Linux": "Linux username",
  "Password Samba": "Samba password",
  "Belum ada Samba share yang dikonfigurasi.": "No Samba share configured yet.",
  "Windows 10/11 memblokir akses guest secara bawaan":
    "Windows 10/11 blocks guest access by default",
  "Share ini akan bekerja dari Linux, macOS, dan Android, tapi Windows menolak login guest lewat SMB2/SMB3 sejak versi 1709 — bukan karena servernya salah. Dua pilihan: beri user Samba dan password lalu matikan Guest OK (dianjurkan), atau longgarkan kebijakan di PC Windows-nya.":
    "This share will work from Linux, macOS, and Android, but Windows has refused guest logons over SMB2/SMB3 since version 1709 — the server is not at fault. Two options: give it a Samba user and password and turn Guest OK off (recommended), or relax the policy on the Windows PC.",
  "Di PC Windows, jalankan PowerShell sebagai Administrator:":
    "On the Windows PC, run PowerShell as Administrator:",

  // ---- storage: pool & nfs ----
  "Gabungkan beberapa folder/disk jadi satu mount point (mergerfs)":
    "Combine several folders/disks into one mount point (mergerfs)",
  "Buat Pool": "Create Pool",
  "Ter-mount": "Mounted",
  "Tidak aktif": "Not active",
  "dari fstab": "from fstab",
  "sumber": "sources",
  "dikelola di /etc/fstab": "managed in /etc/fstab",
  "Folder sumber (satu per baris, minimal dua)": "Source folders (one per line, at least two)",
  "Opsi mount": "Mount options",
  "Bagikan folder ke klien Linux/Unix lewat NFS (/etc/exports)":
    "Share folders with Linux/Unix clients over NFS (/etc/exports)",
  "Tambah Export": "Add Export",
  "Belum aktif": "Not active",
  "terbuka untuk semua": "open to everyone",
  "dari /etc/exports": "from /etc/exports",
  "dikelola di /etc/exports": "managed in /etc/exports",
  "Folder yang dibagikan": "Shared folder",
  "Klien (satu per baris: alamat lalu opsi)": "Clients (one per line: address then options)",
  "Belum ada folder yang dibagikan lewat NFS.": "No folder shared over NFS yet.",

  // ---- firewall & fail2ban ----
  "Tambah Rule": "Add Rule",
  "Aksi": "Action",
  "Port / Protokol": "Port / Protocol",
  "Dari": "From",
  "Tidak ada rule aktif.": "No active rules.",
  "Blokir otomatis IP yang berulang kali gagal login":
    "Automatically ban IPs that repeatedly fail to log in",
  "Tambah Jail": "Add Jail",
  "Jalan": "Running",
  "Enabled, belum jalan": "Enabled, not running",
  "di luar panel": "outside the panel",
  "dikelola di file lain": "managed in another file",
  "Kelola di panel": "Manage in panel",
  "Matikan": "Turn off",
  "Aktifkan": "Turn on",
  "IP diblokir": "IPs banned",
  "Nama jail": "Jail name",
  "Port (opsional)": "Port (optional)",
  "Aktifkan jail ini": "Enable this jail",

  // ---- network ----
  "Interface aktif dengan IP & MAC": "Active interfaces with IP & MAC",
  "Sistem DNS resolver host": "Host DNS resolver",
  "Nameservers (pisahkan dengan koma)": "Nameservers (comma separated)",
  "Simpan DNS": "Save DNS",
  "Token tunnel": "Tunnel token",
  "Hostname di tailnet (opsional)": "Hostname on the tailnet (optional)",
  "Status VPN tidak terbaca. Pastikan helper daemon aktif.":
    "VPN status unavailable. Make sure the helper daemon is running.",

  // ---- docker & files ----
  "Tambah Stack": "Add Stack",
  "Daftarkan": "Register",
  "belum terdaftar": "not registered",
  "berjalan": "running",
  "Nama / ID": "Name / ID",
  "Tidak ada container yang ditemukan.": "No containers found.",
  "Salin path berkas": "Copy file path",
  "Path disalin": "Path copied",
  "Gagal menyalin path": "Could not copy the path",
  "Buka {0} di tab baru": "Open {0} in a new tab",
  "Deploy {0}": "Deploy {0}",
  "Menghentikan {0}": "Stopping {0}",
  "Restart {0}": "Restart {0}",
  "Stop {0}": "Stop {0}",
  "Start {0}": "Start {0}",
  "Tarik image {0}": "Pull images for {0}",
  "{0} selesai.": "{0} finished.",
  "{0} gagal: {1}": "{0} failed: {1}",
  "Buka http://{0}:{1} di tab baru": "Open http://{0}:{1} in a new tab",
  "Browser tidak bisa memutar berkas ini": "Your browser cannot play this file",
  "Wadah atau codec di dalamnya tidak didukung browser ini — MKV dengan HEVC/AV1 dan AVI lama adalah kasus yang paling sering. Berkasnya sendiri tidak rusak: unduh lalu putar dengan VLC atau mpv.":
    "The container or the codec inside it is not supported by this browser — MKV holding HEVC/AV1 and older AVI files are the usual cases. The file itself is fine: download it and play it in VLC or mpv.",
  "Buat Folder": "New Folder",
  "File Baru": "New File",
  "Edit teks": "Edit text",
  "Ubah Permission": "Change Permission",
  "Nama": "Name",
  "Ukuran": "Size",
  "Diubah": "Modified",
  "Izin": "Permissions",

  // ---- pesan, konfirmasi, dan judul dari seluruh view ----
  "Gagal memuat daftar komponen: {0}": "Failed to load the component list: {0}",
  "Gagal memuat daftar proses": "Failed to load the process list",
  "Gagal memuat export: {0}": "Failed to load exports: {0}",
  "Gagal memuat jail: {0}": "Failed to load jails: {0}",
  "Gagal memuat network: {0}": "Failed to load network data: {0}",
  "Gagal memuat pool: {0}": "Failed to load pools: {0}",
  "Gagal memuat rules firewall: {0}": "Failed to load firewall rules: {0}",
  "Gagal memuat status Docker: {0}": "Failed to load Docker status: {0}",
  "Gagal memuat thresholds: {0}": "Failed to load thresholds: {0}",
  "Gagal memuat Samba: {0}": "Failed to load Samba data: {0}",
  "Gagal memuat activity log: {0}": "Failed to load the activity log: {0}",
  "Gagal memulai sesi": "Failed to start the session",
  "Gagal mendaftarkan stack: {0}": "Failed to register the stack: {0}",
  "Gagal mengatur VPN {0}: {1}": "Failed to configure VPN {0}: {1}",
  "Gagal menghapus bookmark: {0}": "Failed to delete the bookmark: {0}",
  "Gagal menghapus config: {0}": "Failed to delete the config: {0}",
  "Gagal menghapus export: {0}": "Failed to delete the export: {0}",
  "Gagal menghapus jail: {0}": "Failed to delete the jail: {0}",
  "Gagal menghapus pool: {0}": "Failed to delete the pool: {0}",
  "Gagal menghapus rule: {0}": "Failed to delete the rule: {0}",
  "Gagal menghapus share: {0}": "Failed to delete the share: {0}",
  "Gagal menghapus stack: {0}": "Failed to delete the stack: {0}",
  "Gagal menghapus user Samba: {0}": "Failed to delete the Samba user: {0}",
  "Gagal menghapus user: {0}": "Failed to delete the user: {0}",
  "Gagal menghapus {0}: {1}": "Failed to delete {0}: {1}",
  "Gagal menghapus: {0}": "Failed to delete: {0}",
  "Gagal menghentikan proses: {0}": "Failed to kill the process: {0}",
  "Gagal mengubah hostname: {0}": "Failed to change the hostname: {0}",
  "Gagal mengubah password: {0}": "Failed to change the password: {0}",
  "Gagal mengubah status jail: {0}": "Failed to change the jail status: {0}",
  "Gagal mengubah status ufw: {0}": "Failed to change the ufw status: {0}",
  "Gagal mengubah status user: {0}": "Failed to change the user status: {0}",
  "Gagal mengubah user: {0}": "Failed to modify the user: {0}",
  "Gagal menjalankan aksi {0}: {1}": "Failed to run action {0}: {1}",
  "Gagal menyimpan .env: {0}": "Failed to save .env: {0}",
  "Gagal menyimpan bookmark: {0}": "Failed to save the bookmark: {0}",
  "Gagal menyimpan compose: {0}": "Failed to save the compose file: {0}",
  "Gagal menyimpan export: {0}": "Failed to save the export: {0}",
  "Gagal menyimpan file: {0}": "Failed to save the file: {0}",
  "Gagal menyimpan jail: {0}": "Failed to save the jail: {0}",
  "Gagal menyimpan pool: {0}": "Failed to save the pool: {0}",
  "Gagal menyimpan rule: {0}": "Failed to save the rule: {0}",
  "Gagal menyimpan share: {0}": "Failed to save the share: {0}",
  "Gagal menyimpan stack: {0}": "Failed to save the stack: {0}",
  "Gagal menyimpan user Samba: {0}": "Failed to save the Samba user: {0}",
  "Gagal menyimpan: {0}": "Failed to save: {0}",
  "Gagal paste: {0}": "Paste failed: {0}",
  "Gagal preview file: {0}": "Failed to preview the file: {0}",
  "Gagal rename: {0}": "Rename failed: {0}",
  "Gagal reset password: {0}": "Failed to reset the password: {0}",
  "Gagal ubah permission: {0}": "Failed to change permissions: {0}",
  "Gagal {0} container: {1}": "Failed to {0} the container: {1}",
  "Gagal melepas blokir: {0}": "Failed to unban: {0}",
  "Gagal memasang {0}: {1}": "Failed to install {0}: {1}",
  "Gagal membaca docker-compose.yml: {0}": "Failed to read docker-compose.yml: {0}",
  "Gagal membaca file .env: {0}": "Failed to read the .env file: {0}",
  "Gagal membaca log: {0}": "Failed to read the log: {0}",
  "Gagal membaca preview": "Failed to read the preview",
  "Gagal membuat folder: {0}": "Failed to create the folder: {0}",
  "Gagal membuat user: {0}": "Failed to create the user: {0}",
  "Gagal membuka direktori: {0}": "Failed to open the directory: {0}",
  "Gagal memperbarui DNS: {0}": "Failed to update DNS: {0}",
  "Tidak bisa membuka file: {0}": "Cannot open the file: {0}",
  "Upload gagal: {0}": "Upload failed: {0}",
  "Aktifkan jail \"{0}\"?": "Enable jail \"{0}\"?",
  "Matikan jail \"{0}\"?": "Disable jail \"{0}\"?",
  "Buat jail \"{0}\"?": "Create jail \"{0}\"?",
  "Hapus jail \"{0}\"?": "Delete jail \"{0}\"?",
  "Simpan perubahan jail \"{0}\"?": "Save changes to jail \"{0}\"?",
  "Buat pool di {0}?": "Create a pool at {0}?",
  "Hapus pool {0}?": "Delete pool {0}?",
  "Lepas pool {0}?": "Unmount pool {0}?",
  "Isi gabungan langsung hilang dari mount point sampai dipasang lagi. Berkasnya TIDAK dihapus — tetap ada di masing-masing disk sumber. Baris /etc/fstab dibiarkan, jadi pool terpasang lagi setelah server boot.":
    "The merged contents disappear from the mount point until it is mounted again. Files are NOT deleted — they stay on each source disk. The /etc/fstab line is left alone, so the pool mounts again after the server boots.",
  "Pool {0} dilepas.": "Pool {0} unmounted.",
  "Pool {0} dipasang.": "Pool {0} mounted.",
  "Gagal melepas pool: {0}": "Failed to unmount the pool: {0}",
  "Gagal memasang pool: {0}": "Failed to mount the pool: {0}",
  "Lepas pool {0}": "Unmount pool {0}",
  "Pasang pool {0}": "Mount pool {0}",
  // Kunci kamus adalah kalimatnya sendiri, jadi kata pendek generik
  // bertabrakan antar halaman: "Lepas" sudah dipakai Fail2ban (Unban) dan
  // "Pasang" dipakai Components (Install), dan yang menang adalah entri
  // terakhir. Label pool karena itu disebut lengkap.
  "Lepas pool": "Unmount pool",
  "Pasang pool": "Mount pool",
  "Simpan perubahan pool {0}?": "Save changes to pool {0}?",
  "Hapus export {0}?": "Delete export {0}?",
  "Simpan perubahan export {0}?": "Save changes to export {0}?",
  "Hapus share Samba \"{0}\"?": "Delete Samba share \"{0}\"?",
  "Simpan share \"{0}\"?": "Save share \"{0}\"?",
  "Simpan perubahan share \"{0}\"?": "Save changes to share \"{0}\"?",
  "Hapus user Samba \"{0}\"?": "Delete Samba user \"{0}\"?",
  "Hapus akun user \"{0}\"?": "Delete user account \"{0}\"?",
  "Simpan perubahan user {0}?": "Save changes to user {0}?",
  "Hapus bookmark ini?": "Delete this bookmark?",
  "Hapus komponen {0} dari sistem?": "Remove component {0} from the system?",
  "Hapus registrasi stack ini?": "Remove this stack registration?",
  "Daftarkan stack \"{0}\" ke panel?": "Register stack \"{0}\" in the panel?",
  "Ubah hostname server jadi \"{0}\"?": "Change the server hostname to \"{0}\"?",
  "Ubah DNS nameserver sistem?": "Change the system DNS nameservers?",
  "Ubah permission jadi {0}?": "Change permissions to {0}?",
  "Simpan ambang peringatan?": "Save alert thresholds?",
  "Simpan docker-compose.yml?": "Save docker-compose.yml?",
  "Timpa file .env stack ini?": "Overwrite this stack's .env file?",
  "Hapus config WireGuard?": "Delete the WireGuard config?",
  "Jalankan \"{0}\" pada service {1}?": "Run \"{0}\" on service {1}?",
  "Jalankan \"docker compose {0}\" pada stack {1}?": "Run \"docker compose {0}\" on stack {1}?",
  "Hapus {0} {1}?": "Delete {0} {1}?",
  "Hapus rule firewall nomor {0}?": "Delete firewall rule number {0}?",
  "Hapus rule firewall {0}?": "Delete firewall rule {0}?",
  "Password baru": "New password",
  "Folder baru": "New folder",
  "Nama folder": "Folder name",
  "File baru": "New file",
  "Nama file": "File name",
  "Buat": "Create",
  "Ada yang gagal saat memuat halaman ini.": "Something failed while loading this page.",
  "Akses jarak jauh yang lewat tunnel ini akan terputus — termasuk sesi Anda kalau membuka dashboard dari alamat tunnel.": "Remote access through this tunnel will drop — including your own session if you opened the dashboard through the tunnel address.",
  "Akun Linux-nya tidak ikut terhapus — hanya kredensial Samba dan namanya di daftar valid users share.": "The Linux account is not deleted — only the Samba credentials and its name in each share's valid users list.",
  "Akun akan dikunci — user ini tidak bisa login sampai dibuka kembali.": "The account will be locked — this user cannot log in until it is unlocked.",
  "Akun dicabut dari sistem dan tidak bisa login lagi. Tindakan ini tidak bisa dibatalkan.": "The account is removed from the system and can no longer log in. This cannot be undone.",
  "Akun ini tidak punya izin membuka halaman tersebut. Butuh hak sudo?": "This account is not allowed to open that page. Does it need sudo rights?",
  "Alamat yang dibuka tidak ada di dashboard ini.": "The address you opened does not exist in this dashboard.",
  "Ambang batas peringatan berhasil disimpan.": "Alert thresholds saved.",
  "Ambang ini berlaku global — sama untuk semua akun yang membuka dashboard.": "These thresholds are global — identical for every account that opens the dashboard.",
  "Ambang persentase warna Amber (Warning) & Merah (Critical) pada tile Dashboard (berlaku global)": "Amber (warning) and red (critical) percentage thresholds for the dashboard tiles (global)",
  "Auth key terakhir yang dipakai (disamarkan).": "Last auth key used (masked).",
  "Baris /etc/fstab ditulis lalu pool di-mount ulang. Folder sumber tidak diubah isinya — file lama tetap di tempatnya dan langsung terlihat lewat mount point.": "The /etc/fstab line is written and the pool is remounted. Source folders are left untouched — existing files stay where they are and appear through the mount point immediately.",
  "Belum ada rule tersimpan. ufw juga nonaktif — nyalakan untuk memfilter traffic.": "No rules saved yet, and ufw is off — turn it on to filter traffic.",
  "Berkas dengan nama sama di folder tujuan akan tertimpa.": "A file with the same name in the destination folder will be overwritten.",
  "Berlaku langsung dan menulis ulang /etc/hosts. Sesi SSH yang memakai nama lama bisa perlu dihubungkan ulang.": "Applies immediately and rewrites /etc/hosts. SSH sessions using the old name may need to reconnect.",
  "Boleh tempel kuncinya saja, atau perintah lengkap dari dashboard Tailscale — yang diambil hanya auth key-nya.": "Paste the key alone, or the full command from the Tailscale dashboard — only the auth key is taken.",
  "Container dihentikan lalu dihapus. Volume dan image tidak ikut terhapus.": "The container is stopped and removed. Volumes and images are kept.",
  "Container {0}: {1} berhasil.": "Container {0}: {1} succeeded.",
  "DNS nameserver berhasil diperbarui.": "DNS nameservers updated.",
  "Definisi share dicabut dari smb.conf. Isi foldernya tidak dihapus.": "The share definition is removed from smb.conf. The folder contents are kept.",
  "File .env berhasil disimpan.": ".env file saved.",
  "File dihapus permanen — tidak masuk Trash.": "The file is deleted permanently — it does not go to Trash.",
  "Folder berhenti dibagikan lewat NFS. Isi foldernya tidak dihapus.": "The folder stops being shared over NFS. Its contents are kept.",
  "Folder beserta seluruh isinya dihapus permanen — tidak masuk Trash.": "The folder and everything in it is deleted permanently — it does not go to Trash.",
  "Folder dibagikan ke klien yang terdaftar, lalu tabel export kernel dimuat ulang (exportfs -ra).": "The folder is shared with the listed clients, then the kernel export table is reloaded (exportfs -ra).",
  "Hanya dihapus dari daftar dashboard. Container yang sedang jalan tidak dimatikan.": "Only removed from the dashboard list. Running containers are not stopped.",
  "Hanya pintasannya yang hilang — folder aslinya tidak disentuh.": "Only the shortcut is removed — the folder itself is untouched.",
  "Hapus juga folder home miliknya?": "Also delete its home folder?",
  "Hostname berhasil diubah.": "Hostname changed.",
  "IP ini bisa mencoba login lagi ke {0}.": "This IP will be able to try logging in to {0} again.",
  "Interface diturunkan dan /etc/wireguard/<iface>.conf dihapus. Private key di dalamnya ikut hilang — salinannya disimpan sebagai .bak di folder yang sama.": "The interface is brought down and /etc/wireguard/<iface>.conf is deleted. The private key inside goes with it — a copy is kept as .bak in the same folder.",
  "Jail diperbarui.": "Jail updated.",
  "Jail mulai memantau lagi setelah fail2ban dimuat ulang.": "The jail starts monitoring again after fail2ban reloads.",
  "Jail {0} diaktifkan.": "Jail {0} enabled.",
  "Jail {0} dibuat.": "Jail {0} created.",
  "Jail {0} dimatikan.": "Jail {0} disabled.",
  "Kalau sudah ada berkas dengan nama itu di folder ini, berkas tersebut akan tertimpa.": "If a file with that name already exists in this folder, it will be overwritten.",
  "Kapasitas hampir penuh pada {0} — bebaskan ruang sebelum layanan gagal menulis.": "Almost out of space on {0} — free some up before services fail to write.",
  "Kelola stack docker-compose": "Manage docker-compose stacks",
  "Komponen {0} berhasil dihapus.": "Component {0} removed.",
  "Komponen {0} berhasil dipasang.": "Component {0} installed.",
  "Koneksi terminal gagal": "Terminal connection failed",
  "Kuota sesi terminal penuh": "Terminal session quota is full",
  "Layanan di stack ini terputus sesaat selama proses berjalan.": "Services in this stack are interrupted briefly while this runs.",
  "Layanan tidak tersedia": "Service unavailable",
  "Login Berhasil": "Login succeeded",
  "Login Gagal": "Login failed",
  "Manajemen Akun User Linux": "Linux User Account Management",
  "Mode simbolik: {0}. Salah set bisa membuat file tidak terbaca atau justru terbuka untuk semua user.": "Symbolic mode: {0}. Setting this wrong can make the file unreadable — or readable by everyone.",
  "Paketnya dicopot. Data yang sudah dibuat komponen ini tetap disimpan, kecuali kamu memilih menghapusnya di bawah.":
    "The package is removed. Data this component created is kept, unless you choose to delete it below.",
  "Hapus data komponen ini juga — termasuk kredensial, koneksi, dan riwayatnya. Tidak bisa dibatalkan.":
    "Delete this component's data as well — including its credentials, connections, and history. This cannot be undone.",
  "Paket dicopot lewat apt. Konfigurasi dan data yang sudah dibuat komponen ini tidak ikut dibersihkan.": "The package is removed via apt. Configuration and data created by this component are left behind.",
  "Panel menulis enabled = false ke jail.local, yang menimpa nilai dari jail.conf/jail.d. Layanan ini berhenti dipantau — percobaan login gagal tidak lagi diblokir otomatis.": "The panel writes enabled = false to jail.local, which overrides jail.conf/jail.d. This service stops being monitored — failed logins are no longer banned automatically.",
  "Password Samba diperbarui.": "Samba password updated.",
  "Password berhasil diubah.": "Password changed.",
  "Password user berhasil direset.": "User password reset.",
  "Permintaan gagal diproses. Cek log service lindash di server.": "The request could not be processed. Check the lindash service log on the server.",
  "Permintaan tidak valid": "Invalid request",
  "Pilih Batal untuk menyimpan isi home directory-nya.": "Choose Cancel to keep the contents of its home directory.",
  "Pool dilepas dan barisnya dibuang dari /etc/fstab. Isi folder sumber TIDAK dihapus — file tetap ada di masing-masing disk, hanya tidak lagi tergabung.": "The pool is unmounted and its line removed from /etc/fstab. Source folder contents are NOT deleted — files stay on each disk, they are simply no longer merged.",
  "Pool diperbarui.": "Pool updated.",
  "Pool {0} dibuat.": "Pool {0} created.",
  "Port yang tadinya difilter rule ini akan mengikuti kebijakan default ufw.": "Ports previously filtered by this rule will follow the ufw default policy.",
  "Reverse proxy tidak bisa menghubungi dashboard.": "The reverse proxy cannot reach the dashboard.",
  "Rule aktif langsung berlaku di kernel. Pastikan port SSH sudah diizinkan agar akses jarak jauh tidak terputus.": "Active rules apply in the kernel immediately. Make sure the SSH port is allowed so remote access is not cut off.",
  "Rule firewall diperbarui.": "Firewall rule updated.",
  "Rute jaringan server bisa berubah setelah tunnel aktif.": "Server network routes may change once the tunnel is up.",
  "Salah satu klien adalah * — folder ini bisa dimount oleh SIAPA PUN yang bisa menjangkau server.": "One of the clients is * — this folder can be mounted by ANYONE who can reach the server.",
  "Semua container di stack ini berhenti dan layanannya mati sampai dinyalakan lagi.": "Every container in this stack stops and its services stay down until started again.",
  "Semua filter berhenti — server menerima koneksi apa pun yang sampai ke port terbuka.": "All filtering stops — the server accepts any connection that reaches an open port.",
  "Sesi tidak valid": "Invalid session",
  "Share \"{0}\" dibuat.": "Share \"{0}\" created.",
  "Share \"{0}\" diperbarui.": "Share \"{0}\" updated.",
  "Share ini Guest OK — siapa pun di jaringan lokal bisa mengaksesnya tanpa password.": "This share is Guest OK — anyone on the local network can access it without a password.",
  "Shell dan keanggotaan grup diganti sesuai isian. Grup yang tidak dicantumkan akan dicabut.": "Shell and group membership are replaced with what you entered. Groups left out will be revoked.",
  "Sinyal SIGTERM dikirim. Data yang belum disimpan proses ini bisa hilang.": "SIGTERM sent. Unsaved data in this process may be lost.",
  "Stack diperbarui.": "Stack updated.",
  "Stack yang sudah jalan ini akan bisa dikelola dari sini (up/down/restart/.env).": "This already-running stack becomes manageable from here (up/down/restart/.env).",
  "Stack {0} terdaftar.": "Stack {0} registered.",
  "Sudah tersambung — tekan Putus dulu untuk memakai auth key lain.": "Already connected — press Disconnect first to use a different auth key.",
  "Token yang sudah terpasang (disamarkan). Tekan Sambung untuk memakainya lagi, atau timpa dengan token lain.": "The token already installed (masked). Press Connect to reuse it, or paste a different one.",
  "Tunnel sedang jalan — tekan Putus dulu untuk memakai token lain.": "The tunnel is running — press Disconnect first to use a different token.",
  "User Samba \"{0}\" ditambahkan.": "Samba user \"{0}\" added.",
  "User {0} berhasil dibuat.": "User {0} created.",
  "jail.local ditulis lalu fail2ban dimuat ulang. Blokir yang sedang berjalan tetap berlaku sampai masa bannya habis.": "jail.local is written and fail2ban reloads. Bans already in effect stay until they expire.",
  "smb.conf ditulis ulang dan smbd dimuat ulang.": "smb.conf is rewritten and smbd reloads.",
  "Jail dibuang dari sistem: pengaturannya di jail.local dihapus, dan stanza dengan nama sama di /etc/fail2ban/jail.d juga dibuang — termasuk definisi bawaan Debian/Ubuntu. Section [DEFAULT] dan jail lain di berkas yang sama tidak disentuh, dan berkas yang diubah dicadangkan sebagai .lindash.bak. Layanan ini berhenti dipantau dan hilang dari daftar.": "The jail is removed from the system: its settings in jail.local are deleted, and the stanza with the same name in /etc/fail2ban/jail.d is dropped too — including the Debian/Ubuntu default. The [DEFAULT] section and other jails in that file are untouched, and any edited file is backed up as .lindash.bak. This service stops being monitored and disappears from the list.",
  "Isi divalidasi Docker dulu; kalau ditolak, file lama tidak disentuh. Versi lama disimpan sebagai .bak. Menyimpan TIDAK men-deploy — jalankan Up/Restart supaya perubahan berlaku.": "The content is validated by Docker first; if it is rejected the old file is untouched. The previous version is kept as .bak. Saving does NOT deploy — run Up/Restart for changes to take effect.",
  "Boleh tempel token telanjang, `sudo cloudflared service install <token>`, atau `cloudflared tunnel run --token <token>` — yang diambil hanya tokennya.": "Paste the bare token, `sudo cloudflared service install <token>`, or `cloudflared tunnel run --token <token>` — only the token is taken.",
  "Daftarkan Compose Stack": "Register Compose Stack",
  "Ganti Password \"{0}\"": "Change Password for \"{0}\"",
  "Ganti Password Sendiri": "Change Your Password",
  "Ganti password Samba {0}": "Change Samba password for {0}",
  "Halaman tidak ditemukan": "Page not found",
  "Hapus Bookmark": "Delete Bookmark",
  "Hapus bookmark {0}": "Delete bookmark {0}",
  "Hapus Komponen": "Remove Component",
  "Hapus Rule FW": "Delete FW Rule",
  "Hapus Share": "Delete Share",
  "Hapus User": "Delete User",
  "Hapus akun": "Delete account",
  "Hapus config WireGuard": "Delete WireGuard config",
  "Hapus config wg": "Delete wg config",
  "Hapus container {0}": "Delete container {0}",
  "Hapus export {0}": "Delete export {0}",
  "Hapus home juga": "Delete home too",
  "Hapus jail {0}": "Delete jail {0}",
  "Hapus pool {0}": "Delete pool {0}",
  "Hapus rule dari sistem": "Delete the rule from the system",
  "Hapus rule {0}": "Delete rule {0}",
  "Hapus share {0}": "Delete share {0}",
  "Hapus stack {0}": "Delete stack {0}",
  "Hapus user Samba {0}": "Delete Samba user {0}",
  "Simpan Bookmark": "Save Bookmark",
  "Simpan Export": "Save Export",
  "Simpan Share": "Save Share",
  "Tambah Bookmark": "Add Bookmark",
  "Tambah Firewall Rule": "Add Firewall Rule",
  "Tambah NFS Export": "Add NFS Export",
  "Tambah Rule FW": "Add FW Rule",
  "Tambah User Samba": "Add Samba User",
  "Ubah Bookmark": "Edit Bookmark",
  "Ubah Compose Stack": "Edit Compose Stack",
  "Ubah Hostname": "Change Hostname",
  "Ubah Hostname Server": "Change Server Hostname",
  "Ubah Password": "Change Password",
  "UFW Nonaktif": "UFW Disabled",
  "Unggah satu folder beserta seluruh isinya": "Upload a folder with everything inside it",
  "Cari proses, PID, user...": "Search process, PID, user…",
  "Config WireGuard dihapus.": "WireGuard config deleted.",
  "{0} dilepas dari {1}.": "{0} unbanned from {1}.",
  "{0} pintasan folder": "{0} folder shortcuts",
  "{0} user terdaftar": "{0} registered users",
  "aksi tidak dikenal": "unknown action",
  "belum jelas": "unknown",
  "tidak ada rule": "no rules",
  "file yang diedit satu grup": "file edited by one group",
  "folder & program, semua boleh baca/masuk": "folders & programs, everyone may read/enter",
  "folder kerja bersama satu grup": "shared work folder for one group",
  "folder privat, hanya pemilik": "private folder, owner only",
  "folder terbatas pemilik & grup": "folder limited to owner & group",
  "Ubah": "Change",
  "Simpan Hostname": "Save Hostname",
  // ---- lengkapi cakupan: teks yang sebelumnya belum diterjemahkan ----
  "Tersambung kembali.": "Reconnected.",
  "{0} belum terpasang": "{0} is not installed",
  "Halaman ini butuh {0} terpasang di sistem.": "This page needs {0} installed on the system.",
  "Rincian pemakaian {0}": "{0} usage breakdown",
  "Login gagal": "Login failed",
  "Password Lama": "Current Password",
  "Password Baru (min 8 karakter)": "New Password (min 8 characters)",
  "Hostname Baru": "New Hostname",
  "mis. homelab-core": "e.g. homelab-core",
  "Grup / Status": "Groups / Status",
  "Tambah User Linux Baru": "Add New Linux User",
  "mis. devuser": "e.g. devuser",
  "Password Awal": "Initial Password",
  "Beri Akses Sudo (Grup sudo)": "Grant Sudo Access (sudo group)",
  "Buat User": "Create User",
  "UID {0} — tidak dapat diubah.": "UID {0} — cannot be changed.",
  "Pilih dari shell yang terpasang di /etc/shells. Service account biasanya pakai /usr/sbin/nologin.": "Pick one of the shells listed in /etc/shells. Service accounts usually use /usr/sbin/nologin.",
  "Grup (pisahkan dengan koma)": "Groups (comma separated)",
  "Grup menentukan akses (mis. sudo = admin, docker = akses socket docker).": "Groups decide access (e.g. sudo = admin, docker = access to the docker socket).",
  "Akun terkunci (tidak bisa login)": "Account locked (cannot log in)",
  "Akun aktif (bisa login)": "Account active (can log in)",
  "Semua aksi sistem & login": "All system actions & logins",
  "Riwayat event login / logout": "Login / logout event history",
  "Tampilkan semua aksi": "Show all actions",
  "Waktu": "Time",
  "Belum ada log aktivitas.": "No activity logged yet.",
  "Ubah User": "Modify User",
  "Bookmark diperbarui.": "Bookmark updated.",
  "Nama Bookmark": "Bookmark Name",
  "mis. Media Downloads": "e.g. Media Downloads",
  "Path Folder Absolut": "Absolute Folder Path",
  "Daftar Bookmarks": "Bookmark List",
  "Buka di File Manager": "Open in File Manager",
  "Belum ada bookmark folder.": "No folder bookmarks yet.",
  "Pasang komponen {0}?": "Install component {0}?",
  "Paket diunduh dan dipasang ke sistem. Bisa berjalan beberapa menit.": "The package is downloaded and installed onto the system. This can take a few minutes.",
  "Service berhenti sampai dinyalakan lagi secara manual.": "The service stays down until it is started again manually.",
  "Service terputus sesaat selama proses berjalan.": "The service is briefly interrupted while this runs.",
  "Memasang {0}… {1} detik berjalan — jangan tutup halaman ini": "Installing {0}… {1} seconds elapsed — do not close this page",
  "Memproses {0}… {1} detik berjalan — jangan tutup halaman ini": "Processing {0}… {1} seconds elapsed — do not close this page",
  "Software opsional yang tidak ikut di instalasi dasar Ubuntu/Debian — {0} dari {1} terpasang": "Optional software not included in a base Ubuntu/Debian install — {0} of {1} installed",
  "{0} terdeteksi": "{0} detected",
  "Pastikan driver amdgpu / nvidia / i915 aktif. Alat vendor (rocm-smi untuk AMD, nvidia-smi untuk NVIDIA, intel_gpu_top untuk Intel) dipasang otomatis oleh installer saat GPU-nya terdeteksi.":
    "Make sure the amdgpu / nvidia / i915 driver is active. Vendor tools (rocm-smi for AMD, nvidia-smi for NVIDIA, intel_gpu_top for Intel) are installed automatically by the installer when a GPU is detected.",
  "WSL meneruskan GPU lewat /dev/dxg, bukan /sys/class/drm, jadi rocm-smi dari repo distro tidak akan melihatnya. Panel menanyakannya ke Windows lewat interop — kalau tetap kosong, pastikan powershell.exe bisa dipanggil dari WSL, lalu tunggu semenit.":
    "WSL exposes the GPU through /dev/dxg, not /sys/class/drm, so a distro-repo rocm-smi will never see it. The panel asks Windows over interop instead — if this stays empty, make sure powershell.exe can be run from WSL, then wait a minute.",
  "VM tanpa PCI passthrough hanya melihat adapter display virtual, bukan GPU. Teruskan kartunya lewat vfio di hypervisor, atau pantau GPU dari host-nya.":
    "A VM without PCI passthrough only sees a virtual display adapter, not a GPU. Pass the card through with vfio on the hypervisor, or monitor the GPU on the host itself.",
  "Container ini tidak dapat passthrough GPU. Tambahkan perangkat /dev/dri dari host, atau pantau GPU dari host-nya langsung.":
    "This container has no GPU passthrough. Add the /dev/dri device from the host, or monitor the GPU on the host itself.",
  "Utilisasi {0}": "{0} utilization",
  "Container berhenti melayani permintaan selama aksi ini berjalan.": "The container stops serving requests while this action runs.",
  "(log kosong)": "(empty log)",
  "docker-compose.yml tersimpan — jalankan Up/Restart agar berlaku.": "docker-compose.yml saved — run Up/Restart to apply it.",
  "Isi lama tertimpa seluruhnya. Container perlu di-recreate (compose up) agar nilai baru terpakai.": "The old content is overwritten entirely. Containers must be recreated (compose up) for the new values to take effect.",
  "Belum ada Compose stack terdaftar maupun berjalan di Docker.": "No Compose stack is registered or running in Docker yet.",
  "Hentikan {0}": "Stop {0}",
  "Jalankan {0}": "Start {0}",
  "Lihat log": "View log",
  "Nama Stack": "Stack Name",
  "mis. Nextcloud": "e.g. Nextcloud",
  "Path Absolut docker-compose.yml": "Absolute Path to docker-compose.yml",
  "Deskripsi (opsional)": "Description (optional)",
  "Divalidasi Docker sebelum ditulis · versi lama disimpan sebagai .bak · menyimpan tidak men-deploy": "Validated by Docker before writing · the previous version is kept as .bak · saving does not deploy",
  "Menyimpan…": "Saving…",
  "Simpan .env": "Save .env",
  "Server menolak permintaan ini.": "The server rejected this request.",
  "Akses ditolak": "Access denied",
  "Server bermasalah": "Server error",
  "Gateway bermasalah": "Gateway error",
  "Service sedang dimulai ulang atau kelebihan beban.": "The service is restarting or overloaded.",
  "Terjadi kesalahan": "Something went wrong",
  "{0} IP diblokir": "{0} IPs blocked",
  "gagal {0} sekarang / {1} total · diblokir {2} total": "{0} failures now / {1} total · {2} bans total",
  "Belum ada jail. Tambahkan sshd untuk mulai memblokir percobaan login SSH yang gagal berulang.": "No jail yet. Add sshd to start blocking repeated failed SSH login attempts.",
  "Namanya harus cocok dengan filter bawaan fail2ban (mis. sshd, nginx-http-auth).": "The name must match a built-in fail2ban filter (e.g. sshd, nginx-http-auth).",
  "ssh atau 22": "ssh or 22",
  "Buat Jail": "Create Jail",
  "Riwayat operasi file (upload, copy, move, delete, rename)": "History of file operations (upload, copy, move, delete, rename)",
  "Riwayat operasi file (upload, copy, move, delete, rename). Disimpan 1 bulan, setelah itu dihapus otomatis.":
    "History of file operations (upload, copy, move, delete, rename). Kept for 1 month, then deleted automatically.",
  "Semua alert panel — berhasil, gagal, peringatan, info. Disimpan 1 bulan, setelah itu dihapus otomatis.":
    "Every panel alert — success, failure, warning, info. Kept for 1 month, then deleted automatically.",
  "Semua aksi sistem & login. Disimpan 2 tahun, setelah itu dihapus otomatis.":
    "All system actions & logins. Kept for 2 years, then deleted automatically.",
  "Riwayat event login / logout. Disimpan 2 tahun, setelah itu dihapus otomatis.":
    "Login / logout event history. Kept for 2 years, then deleted automatically.",
  "Berhasil": "Success",
  "Gagal": "Failed",
  "Peringatan": "Warning",
  "Info": "Info",
  "Semua": "All",
  "Status": "Status",
  "Pesan": "Message",
  "Halaman": "Page",
  "Detail": "Detail",
  "Belum ada alert yang tercatat.": "No alerts recorded yet.",
  "Belum ada alert dengan status {0}.": "No alerts with status {0} yet.",
  "Operasi": "Operation",
  "Sumber": "Source",
  "Tujuan": "Destination",
  "Belum ada log operasi file.": "No file operations logged yet.",
  "File dibuat.": "File created.",
  "Perubahan tersimpan.": "Changes saved.",
  "Simpan bookmark": "Save bookmark",
  "Nama bookmark": "Bookmark name",
  "Bookmark disimpan.": "Bookmark saved.",
  "Ganti nama jadi \"{0}\"?": "Rename to \"{0}\"?",
  "Ganti nama": "Rename",
  "Salin {0} ke sini?": "Copy {0} here?",
  "Pindahkan {0} ke sini?": "Move {0} here?",
  "{0} item": "{0} items",
  "{0} item terpilih": "{0} items selected",
  "Pilih semua": "Select all",
  "Batal pilih": "Clear selection",
  "Download (.zip)": "Download (.zip)",
  "Hapus {0} item terpilih?": "Delete {0} selected items?",
  "{0} item dihapus.": "{0} items deleted.",
  "{0} item gagal dihapus.": "{0} items could not be deleted.",
  "{0} item gagal dipaste.": "{0} items could not be pasted.",
  "Salin": "Copy",
  "Pindahkan": "Move",
  "Simpan folder saat ini ke Bookmarks": "Save the current folder to Bookmarks",
  "Modifikasi": "Modified",
  "Direktori kosong": "Empty directory",
  "Ditulis dengan izin akun Linux Anda · maksimal 1 MB · file biner tidak bisa dibuka di sini": "Written with your Linux account's permissions · 1 MB maximum · binary files cannot be opened here",
  "Nama baru": "New name",
  "file umum, semua boleh baca": "ordinary file, everyone may read",
  "file privat, mis. kunci & kredensial": "private file, e.g. keys & credentials",
  "semua akses — hindari": "full access — avoid",
  "mode saat ini": "current mode",
  "Nyalakan ufw?": "Enable ufw?",
  "Matikan ufw?": "Disable ufw?",
  "Nyalakan": "Enable",
  "Konfigurasi port filter host": "Host port filter configuration",
  "UFW Aktif": "UFW Enabled",
  "Matikan ufw": "Disable ufw",
  "Nyalakan ufw": "Enable ufw",
  "ufw belum terpasang di host ini.": "ufw is not installed on this host.",
  "Pasang dengan apt install ufw lewat SSH, atau lewat menu Components (jika diotomasi di sana).": "Install it with apt install ufw over SSH, or from the Components menu (if automated there).",
  "Rule di bawah sudah tersimpan tapi belum berlaku — ufw masih nonaktif.": "The rules below are saved but not in effect — ufw is still disabled.",
  "ufw tidak bisa mengubah rule di tempat — rule lama dihapus lalu yang baru ditambahkan, jadi posisinya pindah ke urutan terakhir.": "ufw cannot edit a rule in place — the old rule is deleted and the new one appended, so it moves to the end of the list.",
  "mis. 80, 443, 22": "e.g. 80, 443, 22",
  "Protokol": "Protocol",
  "Dari (sumber)": "From (source)",
  "kosongkan jika ingin Anywhere — atau 192.168.1.10 / 10.0.0.0/8": "leave empty for Anywhere — or 192.168.1.10 / 10.0.0.0/8",
  "Simpan Rule": "Save Rule",
  "Bahasa": "Language",
  "Server": "Server",
  "Panel ini mengelola mesin Linux apa adanya: akun, berkas, layanan, dan jaringan. Tidak ada basis data pengguna terpisah — semua yang Anda lihat adalah keadaan sistem yang sebenarnya.": "This panel manages the Linux machine as it is: accounts, files, services, and networking. There is no separate user database — everything you see is the actual state of the system.",
  "Masuk ke server": "Sign in to the server",
  "Masuk ke {0}": "Sign in to {0}",
  "Pakai username dan password akun Linux Anda di mesin ini. Tidak ada akun terpisah.": "Use the username and password of your Linux account on this machine. There is no separate account.",
  "mis. oxidilily": "e.g. oxidilily",
  "Memeriksa…": "Checking…",
  "{0} sumber": "{0} sources",
  "{0} / {1} terpakai · sisa {2}": "{0} / {1} used · {2} free",
  "Belum ada pool. Buat satu untuk menggabungkan beberapa disk jadi satu folder — file lama di tiap disk tetap utuh dan langsung terlihat menyatu.": "No pool yet. Create one to merge several disks into a single folder — existing files on each disk stay intact and appear merged right away.",
  "Buat Disk Pool": "Create Disk Pool",
  "Mount point adalah kunci pool di /etc/fstab — hapus lalu buat baru untuk memindahkannya.": "The mount point is the pool's key in /etc/fstab — delete and recreate the pool to move it.",
  "category.create=pfrd menyebar file baru ke semua disk, dipilih acak dengan bobot sisa ruang — disk yang lebih besar menerima bagian lebih banyak dan semuanya penuh pada waktu berdekatan. Ganti ke mfs kalau justru ingin satu disk terisi penuh dulu sebelum pindah ke disk berikutnya; nofail menjaga server tetap bisa boot kalau pool gagal di-mount.":
    "category.create=pfrd spreads new files across every disk, picked at random weighted by free space — larger disks take a bigger share and they all fill up at around the same time. Switch to mfs if you would rather fill one disk completely before moving to the next; nofail keeps the server bootable if the pool fails to mount.",
  "Resolusi nama seluruh server memakai daftar ini. Salah isi bisa memutus akses internet server.": "The whole server resolves names through this list. A wrong entry can cut off the server's internet access.",
  "tempel auth key, atau perintah `sudo tailscale up --auth-key=…`": "paste the auth key, or the `sudo tailscale up --auth-key=…` command",
  "tempel token, atau perintah `cloudflared service install <token>`": "paste the token, or the `cloudflared service install <token>` command",
  "Isi wg0.conf": "wg0.conf contents",
  "Wajib ada section [Interface]. Disimpan ke /etc/wireguard/wg0.conf (mode 0600).": "An [Interface] section is required. Saved to /etc/wireguard/wg0.conf (mode 0600).",
  "Export {0} ke jaringan?": "Export {0} to the network?",
  "Export diperbarui.": "Export updated.",
  "Export {0} dibuat.": "Export {0} created.",
  "Opsi kosong memakai {0}. Gunakan CIDR agar hanya jaringan lokal yang bisa mount — * membuka folder untuk siapa pun yang bisa menjangkau server.": "An empty option list uses {0}. Use CIDR so only the local network can mount it — * opens the folder to anyone who can reach the server.",
  "Hentikan proses PID {0}?": "Stop process PID {0}?",
  "{0} total proses": "{0} processes total",
  "Kill proses milik sendiri": "Kill your own process",
  "Kill (perlu sudo)": "Kill (needs sudo)",
  "{0} share memakai user ini": "{0} shares use this user",
  "Nonaktifkan {0}": "Disable {0}",
  "Aktifkan {0}": "Enable {0}",
  "Belum ada user Samba. Akun Linux (mis. yang dibuat di Settings → Akun) tidak otomatis bisa login share — daftarkan di sini dulu dengan password Samba-nya sendiri.": "No Samba user yet. A Linux account (e.g. one created in Settings → Account) cannot log in to a share automatically — register it here first with its own Samba password.",
  "Harus akun Linux yang sudah ada — Samba memetakan login ke UID Unix.": "Must be an existing Linux account — Samba maps the login to a Unix UID.",
  "Tambah Samba Share": "Add Samba Share",
  "mis. Media": "e.g. Media",
  "Nama share adalah kunci di smb.conf — hapus lalu buat baru kalau ingin ganti nama.": "The share name is its key in smb.conf — delete and recreate it to rename.",
  "Guest OK aktif — share ini terbuka tanpa login, jadi daftar user diabaikan smbd. Matikan Guest OK dulu kalau ingin membatasi ke user tertentu.": "Guest OK is on — this share is open without a login, so smbd ignores the user list. Turn Guest OK off first to limit it to specific users.",
  "Belum ada user Samba. Tambahkan dulu di panel User Samba — akun Linux saja tidak cukup.": "No Samba user yet. Add one in the Samba Users panel first — a Linux account alone is not enough.",
  "nonaktif": "disabled",
  "tambahan, mis. @grup": "extra entries, e.g. @group",
  "Kosong = semua user Samba yang terdaftar boleh login ke share ini.": "Empty = every registered Samba user may log in to this share.",
  "Set password Samba untuk share ini (opsional)": "Set a Samba password for this share (optional)",
  "Sesi terminal ditutup": "Terminal session closed",
  "Sesi login tidak valid. Muat ulang halaman untuk login ulang.": "Invalid login session. Reload the page to sign in again.",
  "Akses terminal butuh sudo.": "Terminal access requires sudo.",
  "Kuota sesi terminal penuh. Tutup salah satu sesi aktif, atau naikkan kapasitas di menu Settings.": "The terminal session quota is full. Close an active session, or raise the capacity in the Settings menu.",
  "Helper daemon tidak bisa memulai PTY. Periksa log helper.": "The helper daemon could not start a PTY. Check the helper log.",
  "Kuota sesi terminal penuh (503). Tutup salah satu sesi aktif.": "The terminal session quota is full (503). Close an active session.",
  "Koneksi terminal terputus (kode {0}).": "Terminal connection lost (code {0}).",
  "Koneksi terminal terputus (kode {0}) setelah 3× percobaan ulang.": "Terminal connection lost (code {0}) after 3 reconnect attempts.",
  "Koneksi terputus — mencoba lagi…": "Connection lost — retrying…",
  "Shell web interaktif": "Interactive web shell",
  "Sesi": "Sessions",
  "Login": "Logins",
  "Core": "Cores",
  "Buka ulang sesi": "Reopen session",
  "Sesi terminal dihapus dari panel": "Terminal session cleared from the panel",
  "Hapus semua sesi terminal": "Clear all terminal sessions",
  "Semua sesi terminal ditutup, termasuk yang sedang terbuka di tab ini.": "Every terminal session is closed, including the one open in this tab.",
  "Hapus sesi": "Clear sessions",
  "{0} sesi terminal ditutup.": "{0} terminal session(s) closed.",
  "Gagal menghapus sesi: {0}": "Failed to clear sessions: {0}",
  "Buka": "Open",
  "Sesi di server mungkin masih aktif — periksa koneksi lalu muat ulang halaman.":
    "The session on the server may still be active — check your connection and reload the page.",
  "Buka antarmuka {0} di tab baru": "Open the {0} interface in a new tab",
  "Tidak bisa membuka {0}: {1}": "Could not open {0}: {1}",

  // ---- AI → AI Agent ----
  "AI Agent": "AI Agent",
  "Antarmuka interaktif AI Agent CLI — Ctrl+C memuat ulang agent, bukan menutup sesi":
    "Interactive AI Agent CLI — Ctrl+C reloads the agent instead of closing the session",
  "Sesi CLI AI Agent ditutup": "AI Agent CLI session closed",
  "Belum ada": "Not installed",
  "{0} Belum Terpasang": "{0} Is Not Installed",
  "Komponen {0} belum dipasang di sistem ini. Anda dapat memasangnya dari menu Components.":
    "The {0} component is not installed on this system. You can install it from the Components page.",
  "Buka Menu Components": "Open Components page",
  "Buka terminal AI Agent": "Open the AI Agent terminal",
  "Buka Agent": "Open Agent",
  "Alat & skill wajib": "Required tools & skills",
  "Pasang {0} alat yang kurang": "Install {0} missing tool(s)",
  "Pemangkas token untuk keluaran perintah shell":
    "Token trimmer for shell command output",
  "Knowledge graph kode untuk penelusuran repo":
    "Code knowledge graph for exploring the repo",
  "Harness lazy senior dev level ultra + skill audit/review/debt":
    "Lazy senior dev harness at ultra level + audit/review/debt skills",
  "Rust Token Killer — proxy CLI yang memangkas keluaran perintah sebelum masuk konteks AI Agent.":
    "Rust Token Killer — a CLI proxy that trims command output before it reaches the AI Agent context.",
  "Knowledge graph kode lewat parsing AST lokal — dipakai AI Agent untuk memetakan repo tanpa membaca berkas satu per satu.":
    "Code knowledge graph via local AST parsing — used by AI Agents to map a repo without reading files one by one.",
  "Harness \"lazy senior dev\" level ultra + bundle skill ponytail-audit/review/debt.":
    "\"Lazy senior dev\" harness at ultra level + the ponytail-audit/review/debt skill bundle.",
  "Password akun ini wajib diganti. Banner SSH \"Default password must be changed\" muncul karena akun masih memakai password bawaan installer.": "This account's password must be changed. The SSH banner \"Default password must be changed\" appears because the account still uses the installer default.",
  "Ganti sekarang": "Change now",
  "Guest OK akan dinonaktifkan": "Guest OK will be turned off",
  "Share ini punya daftar user terbatas — Guest OK tidak bisa diaktifkan bersamaan (smbd mengabaikan valid users saat guest ok = yes). Lanjut tanpa Guest OK?": "This share has a limited user list — Guest OK cannot be enabled together with it (smbd ignores valid users when guest ok = yes). Continue without Guest OK?",
  "Lanjut tanpa Guest OK": "Continue without Guest OK",
  "Coba lagi": "Try again",
  "{0} {1} dari {2} {3} terpakai": "{0} {1} of {2} {3} used",
  "{0} / {1} berjalan": "{0} / {1} running",
  // ---- label aksi pada activity log (dikirim backend) ----
  "Lainnya": "Other",
  "aksi container": "container action",
  "buat user": "create user",
  "buka sesi terminal": "open terminal session",
  "daftar stack": "register stack",
  "ganti password sendiri": "change own password",
  "hapus export": "delete export",
  "hapus jail": "delete jail",
  "hapus pool": "delete pool",
  "hapus rule": "delete rule",
  "hapus share": "delete share",
  "hapus user": "delete user",
  "hapus user Samba": "delete Samba user",
  "lepas blokir IP": "unban IP",
  "reset password user lain": "reset another user's password",
  "simpan export": "save export",
  "simpan jail": "save jail",
  "simpan pool": "save pool",
  "simpan share": "save share",
  "simpan user Samba": "save Samba user",
  "tambah rule": "add rule",
  "tulis file": "write file",
  "ubah ambang": "change thresholds",
  "ubah DNS": "change DNS",
  "ubah docker-compose.yml": "edit docker-compose.yml",
  "ubah .env": "edit .env",
  "ubah rule": "edit rule",
  "ubah stack": "edit stack",
  "ubah user": "modify user",
  "Isi token lalu Sambung — panel memasang ulang service dengan token itu.": "Enter the token then press Connect — the panel reinstalls the service with it.",
  "Critical (Merah %)": "Critical (Red %)",
  "Tutup notifikasi": "Dismiss notification",
  "Selamat datang kembali, {0}": "Welcome back, {0}",
  "200 baris terakhir · {0}": "last 200 lines · {0}",
  "Naik": "Up",
  "Mode Oktal": "Octal Mode",
  "Hubungkan {0}?": "Connect {0}?",
  "Putuskan {0}?": "Disconnect {0}?",
  "Hubungkan {0}": "Connect {0}",
  "Hubungkan": "Connect",
  "Putuskan": "Disconnect",
  "Lepas blokir {0}?": "Unban {0}?",
  "Lepas": "Unban",
  "Lanjutkan": "Continue",
  "{0} · {1} · sisa {2} · {3}": "{0} · {1} · {2} free · {3}",
  "{0} / {1} · {2} mount · {3} disk belum dipakai": "{0} / {1} · {2} mounts · {3} unused disk(s)",
  "{0} · belum di-mount{1}": "{0} · not mounted{1}",
  "{0} · belum di-mount — klik untuk format & mount{1}": "{0} · not mounted — click to format & mount{1}",
  "belum dipakai": "unused",
  "Versi baru panel tersedia.": "A new panel version is available.",
  "Buka menu Update di sidebar untuk memasangnya.": "Open the Update menu in the sidebar to install it.",
  "{0} siap dipakai di {1}.": "{0} is ready to use at {1}.",
  "Mount point": "Mount point",
  "Filesystem": "Filesystem",
  "Mount saja": "Mount only",
  "Format ulang": "Reformat",
  "Format & mount": "Format & mount",
  "Menyiapkan…": "Preparing…",
  "Folder dibuat kalau belum ada. Entri fstab ditulis memakai UUID disk dan opsi nofail, jadi server tetap bisa boot walau disknya dilepas.": "The folder is created if missing. The fstab entry uses the disk UUID and the nofail option, so the server still boots if the disk is removed.",
  "Disk akan diformat — pastikan tidak ada data yang masih dibutuhkan di sana. Kalau ternyata sudah berisi filesystem, panel berhenti dan menanyakannya dulu.": "The disk will be formatted — make sure nothing there is still needed. If it turns out to already hold a filesystem, the panel stops and asks first.",
  "Disk ini sudah berisi filesystem {0}. Memformatnya menghapus seluruh isinya.": "This disk already holds a {0} filesystem. Formatting erases everything on it.",
  // Kata di bawah kebetulan sama di dua bahasa, tapi tetap dicatat karena
  // pemeriksa membacanya sebagai kata Indonesia.
  "total": "total",
  "folder": "folder",
  "Folder": "Folder",
  "Upload Folder": "Upload Folder",
  "Core {0}": "Core {0}",

  // ---- pembaruan panel ----
  "Pembaruan panel": "Panel update",
  "Yang akan ikut terpasang ({0} commit)": "What this will install ({0} commits)",
  "Commit terbaru di GitHub ({0})": "Latest commits on GitHub ({0})",
  "Versi terpasang tidak ditemukan di riwayat itu, jadi sebagian mungkin sudah ada di mesin ini.":
    "The installed version was not found in that history, so some of these may already be on this machine.",
  "Memeriksa versi…": "Checking version…",
  "Terpasang: {0}": "Installed: {0}",
  "Versi terpasang tidak terbaca — sumber belum ada di mesin ini.":
    "Installed version unreadable — the source is not on this machine yet.",
  "Ada versi baru di GitHub: {0}": "A newer version is on GitHub: {0}",
  "Sudah versi terbaru.": "Already up to date.",
  "Versi di GitHub tidak terbaca — cek koneksi mesin ini ke github.com.":
    "The GitHub version could not be read — check this machine's connection to github.com.",
  "Belum ada pembaruan yang dijalankan di mesin ini.":
    "No update has been run on this machine yet.",
  "Jalankan pembaruan panel?": "Run the panel update?",
  "Sumber ditarik ulang dari GitHub, dibangun ulang, lalu kedua service di-restart. Panel akan terputus sebentar di akhir proses, dan build bisa memakan beberapa menit di mesin kecil.":
    "The source is pulled again from GitHub, rebuilt, then both services are restarted. The panel drops briefly at the end, and the build can take several minutes on a small machine.",
  "Perbarui": "Update",
  "Perbarui sekarang": "Update now",
  "Memperbarui…": "Updating…",
  "Service sedang di-restart — menunggu panel hidup lagi…":
    "Services are restarting — waiting for the panel to come back…",
  "Pembaruan berjalan. Modal boleh ditutup, prosesnya jalan terus di server.":
    "Update running. You can close this dialog — it keeps going on the server.",
  "Pembaruan gagal (exit {0}). Baca ekor log di atas.":
    "Update failed (exit {0}). Read the log tail above.",
  "Pembaruan selesai. Muat ulang halaman untuk memakai versi baru.":
    "Update finished. Reload the page to use the new version.",

  // ---- WireGuard mode server ----
  "Jadikan server": "Make this a server",
  "Atau tekan Sambung untuk memakai mesin ini sebagai klien dengan menempel config.":
    "Or press Connect to use this machine as a client by pasting a config.",
  "Subnet tunnel": "Tunnel subnet",
  "Port UDP": "UDP port",
  "Endpoint untuk klien": "Endpoint for clients",
  "Endpoint adalah alamat yang dituju klien dari luar — IP publik atau hostname. Server di balik NAT tidak bisa menebaknya sendiri, dan port UDP-nya harus diteruskan router.":
    "The endpoint is the address clients reach from outside — a public IP or hostname. A server behind NAT cannot guess it, and its UDP port must be forwarded by the router.",
  "Siapkan": "Set up",
  "Siapkan server WireGuard?": "Set up the WireGuard server?",
  "Panel membuat kunci server, menulis config, menyalakan IP forwarding, menambah aturan NAT, dan membuka port UDP di firewall kalau ufw aktif.":
    "The panel creates the server key, writes the config, enables IP forwarding, adds the NAT rules, and opens the UDP port in the firewall if ufw is active.",
  "Server WireGuard siap.": "WireGuard server is ready.",
  "Gagal menyiapkan server: {0}": "Could not set up the server: {0}",
  "Gagal membaca config WireGuard: {0}": "Could not read the WireGuard config: {0}",
  "Config klien terpasang di {0}. Mode server tidak aktif.":
    "A client config is installed at {0}. Server mode is off.",
  "Tambah klien": "Add client",
  "Tambah klien WireGuard": "Add a WireGuard client",
  "Nama klien": "Client name",
  "mis. laptop-kerja": "e.g. work-laptop",
  "Gagal menambah klien: {0}": "Could not add the client: {0}",
  "Belum ada klien. Tambahkan satu untuk mendapat config + QR.":
    "No clients yet. Add one to get its config and QR code.",
  "Klien": "Client",
  "Alamat": "Address",
  "Handshake": "Handshake",
  "Hapus klien {0}?": "Delete client {0}?",
  "Hapus klien {0}": "Delete client {0}",
  "Klien ini langsung kehilangan akses ke tunnel. Config yang ada di perangkatnya tidak akan bisa dipakai lagi.":
    "This client loses tunnel access immediately. The config on its device stops working.",
  "Klien dihapus.": "Client deleted.",
  "Gagal menghapus klien: {0}": "Could not delete the client: {0}",
  "endpoint belum tercatat": "endpoint not recorded",
  "belum pernah": "never",
  "{0} dtk lalu": "{0}s ago",
  "{0} mnt lalu": "{0}m ago",
  "{0} jam lalu": "{0}h ago",
  "{0} hari lalu": "{0}d ago",
  "Config klien {0}": "Config for {0}",
  "Simpan sekarang — private key-nya tidak disimpan di server, jadi config ini tidak bisa ditampilkan lagi.":
    "Save it now — the private key is not kept on the server, so this config cannot be shown again.",
  "Scan dari app WireGuard di HP: Tambah tunnel → Buat dari QR code.":
    "Scan it in the WireGuard phone app: Add tunnel → Create from QR code.",
  "Salin config": "Copy config",
  "Tersalin": "Copied",
  "Selesai": "Done",
  "Browser menolak akses clipboard — salin manual dari kotak di atas.":
    "The browser denied clipboard access — copy manually from the box above.",

  // ---- uninstall panel ----
  "Uninstall panel": "Uninstall the panel",
  "Pilih sejauh mana yang dihapus. Tidak ada langkah yang bisa dibatalkan setelah dimulai.":
    "Choose how much gets removed. Nothing can be undone once it starts.",
  "Hapus panel saja": "Remove the panel only",
  "Service dihentikan, unit systemd & binary dihapus":
    "Services stopped, systemd units and binaries removed",
  "Konfigurasi PAM dan sumber di /usr/local/src dihapus":
    "PAM config and the source in /usr/local/src removed",
  "Database panel, akun panel, dan bookmark tetap ada":
    "Panel database, panel accounts, and bookmarks are kept",
  "Hapus panel dan folder/file panel": "Remove the panel and its files",
  "Semua yang di atas": "Everything above",
  "Database panel, kunci sesi, dan berkas kerja pembaruan dihapus":
    "Panel database, session key, and update work files removed",
  "Akun sistem linux-dashboard dihapus": "The linux-dashboard system account is removed",
  "Hapus total (termasuk components)": "Remove everything (components included)",
  "Server DNS Technitium ikut dicopot — zona, blocklist, dan setelannya hilang; resolusi nama mesin dikembalikan ke systemd-resolved":
    "The Technitium DNS server is removed too — its zones, blocklists, and settings are gone; name resolution goes back to systemd-resolved",
  "SEMUA components yang bisa dipasang panel dicopot, termasuk Docker, Node.js, Tailscale, cloudflared, dan alat AI":
    "EVERY component the panel can install is removed, including Docker, Node.js, Tailscale, cloudflared, and the AI tools",
  "Token tunnel cloudflared dan data component (mis. password 9router) ikut dihapus":
    "The cloudflared tunnel token and component data (e.g. the 9router password) are deleted too",
  "Image & volume Docker di /var/lib/docker TIDAK dihapus — isinya milik container Anda":
    "Docker images & volumes in /var/lib/docker are NOT deleted — they belong to your containers",
  "Berkas pribadi di ~/DATA setiap akun tidak pernah ikut dihapus, mode mana pun. Akun Linux Anda juga tidak — yang dihapus hanya akun sistem linux-dashboard milik service. Konfigurasi Samba, NFS, dan WireGuard ditinggalkan apa adanya; pada mode hapus total, izin firewall milik komponen yang dicopot ikut dicabut.":
    "Personal files in each account's ~/DATA are never deleted, in any mode. Neither are your Linux accounts — only the linux-dashboard system account used by the service is removed. Samba, NFS and WireGuard configuration is left untouched; in full-removal mode, firewall permissions belonging to the removed components are revoked with them.",
  "Konfirmasi uninstall": "Confirm uninstall",
  "Password root": "Root password",
  "Password akun {0}": "Password for {0}",
  "OK": "OK",
  "Uninstall": "Uninstall",
  "Uninstall berjalan.": "Uninstall is running.",
  "Panel berhenti sebentar lagi dan halaman ini akan mati sendiri. Jalannya proses tercatat di /var/log/linux-dashboard-uninstall.log.":
    "The panel stops shortly and this page will go down with it. The run is logged to /var/log/linux-dashboard-uninstall.log.",

  // ---- print server ----
  "Printer": "Printers",
  "Antrean cetak CUPS. Printer di sini bisa dipakai lewat menu Print di file manager.":
    "CUPS print queues. Printers listed here can be used from the Print menu in the file manager.",
  "Tambah Printer": "Add Printer",
  "default": "default",
  "antrean dimatikan": "queue disabled",
  "dibagikan ke jaringan": "shared on network",
  "Belum ada printer terdaftar. Tambahkan satu supaya menu Print di file manager bisa dipakai.":
    "No printers registered yet. Add one so the Print menu in the file manager becomes usable.",
  "Antrean cetak": "Print queue",
  "Pekerjaan yang sedang menunggu atau sedang dicetak": "Jobs waiting or currently printing",
  "Antrean kosong.": "The queue is empty.",
  "Nama antrean": "Queue name",
  "Huruf, angka, titik, dan garis saja — CUPS menolak spasi.":
    "Letters, digits, dots and dashes only — CUPS rejects spaces.",
  "Perangkat": "Device",
  "Perangkat (memindai…)": "Device (scanning…)",
  "— pilih perangkat terdeteksi —": "— pick a detected device —",
  "Printer jaringan tanpa penemuan otomatis bisa diisi manual, mis. socket://IP:9100 atau ipp://IP/ipp/print.":
    "Network printers without auto-discovery can be typed in, e.g. socket://IP:9100 or ipp://IP/ipp/print.",
  "Driver": "Driver",
  "Printer terbitan 2015 ke atas hampir selalu jalan dengan IPP Everywhere tanpa driver tambahan.":
    "Printers made from 2015 onward almost always work with IPP Everywhere, no extra driver needed.",
  "Deskripsi": "Description",
  "Lokasi": "Location",
  "Ruang depan": "Front office",
  "Bagikan ke jaringan (klien lain bisa mencetak lewat server ini)":
    "Share on the network (other clients can print through this server)",
  "Antrean dan konfigurasinya dihapus dari CUPS. Pekerjaan yang belum tercetak ikut hilang.":
    "The queue and its configuration are removed from CUPS. Jobs not yet printed are lost with it.",
  "Print": "Print",
  "Salinan": "Copies",
  "Ukuran kertas": "Paper size",
  "bawaan printer": "printer default",
  "Sisi": "Sides",
  "satu sisi": "one-sided",
  "bolak-balik (sisi panjang)": "two-sided (long edge)",
  "bolak-balik (sisi pendek)": "two-sided (short edge)",
  "Mengirim…": "Sending…",
  "Belum ada printer yang terdaftar di server ini. Tambahkan satu di Settings → Print server, lalu coba lagi.":
    "No printers are registered on this server yet. Add one under Settings → Print server, then try again.",
  "Pantau progresnya di Settings → Print server.": "Track its progress under Settings → Print server.",
  "— pilih driver —": "— pick a driver —",
  "Deteksi printer": "Detect printers",
  "Colok printer USB atau sambungkan ke jaringan, lalu jalankan deteksi. Driver yang kurang dipasang dari sini juga.":
    "Plug in a USB printer or connect one to the network, then run detection. Missing drivers are installed from here too.",
  "Deteksi": "Detect",
  "Memindai…": "Scanning…",
  "Belum dipindai. Tekan Deteksi untuk mencari printer yang terpasang.":
    "Not scanned yet. Press Detect to look for connected printers.",
  "Tidak ada printer terdeteksi. Pastikan kabel USB tersambung dan printer menyala.":
    "No printers detected. Check that the USB cable is connected and the printer is powered on.",
  "sudah terdaftar": "already added",
  "driver siap": "driver ready",
  "driver belum ada": "driver missing",
  "Perlu paket: {0}": "Needs package: {0}",
  "siap dipakai": "ready to use",
  "Tambahkan": "Add",
  "Menambahkan…": "Adding…",
  "Pasang driver": "Install driver",
  "Memasang…": "Installing…",
  "Driver {0} terpasang": "Driver {0} installed",
  "Penemuan lewat mDNS/Bonjour sedang mati karena komponen avahi belum aktif. Printer USB dan printer yang menjawab SNMP tetap terdeteksi, tapi printer jaringan modern mungkin tidak muncul — tambahkan lewat URI manual, atau pasang komponen avahi.":
    "Discovery over mDNS/Bonjour is off because the avahi component is not active. USB printers and printers that answer SNMP are still detected, but modern network printers may not show up — add them by manual URI, or install the avahi component.",
  "Buka Components": "Open Components",
  "Memasang {0} — jangan tutup halaman ini": "Installing {0} — do not close this page",
  "Memproses {0} — jangan tutup halaman ini": "Working on {0} — do not close this page",
  "Kemajuan pemasangan": "Installation progress",
  "Sedang dipasang": "Installing",
  "Sedang diproses": "Working",
  "menyiapkan pemasangan": "preparing the install",
  "memperbarui daftar paket": "updating the package list",
  "mengunduh paket": "downloading packages",
  "memasang paket": "installing packages",
  "memasang runtime Node.js": "installing the Node.js runtime",
  "mengunduh dan memasang paket npm": "downloading and installing the npm package",
  "menjalankan skrip resmi Tailscale": "running the official Tailscale script",
  "menjalankan skrip resmi Technitium DNS": "running the official Technitium DNS script",
  "menjalankan skrip resmi Hermes": "running the official Hermes script",
  "menjalankan skrip resmi rtk": "running the official rtk script",
  "memasang graphify lewat pipx": "installing graphify with pipx",
  "Printer USB tidak mendukung IPP Everywhere — pilih driver yang cocok dari daftar, kalau tidak cetakan akan keluar kosong.":
    "USB printers do not support IPP Everywhere — pick a matching driver, otherwise pages come out blank.",
})
